### ISSUE TITLE
位置没生效

### ISSUE THREAD

**Issue by xiatian12345** [LoseNine/ruyiBrowser#3]
"position\":{\"longitude\":116.231407,\"latitude\":39.951754,

纬度
31°7′48.72000″N
经度
104°22′54.48000″E

环境：
版本	Windows 11 家庭版
版本	23H2
安装日期	‎2024/‎3/‎24
操作系统版本	22631.3296
体验	Windows Feature Experience Pack 1000.22687.1000.0

设备名称	P739
处理器	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	笔支持

**Comment by LoseNine** [comment]
只能是你参数写错了
